# Generated by Django 5.2.13 on 2026-05-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_calllog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
